src/servers/ZoneServer/commands/hax.ts, src/servers/ZoneServer/zonepackethandlers.ts, src/servers/ZoneServer/zoneserver.ts, src/types/zoneserver.ts
Its for singleplayer only, so i based the "health" on adding value to a variable and didnt bother about seperate health for multiple vehicles. If we apply siren or headlights then we cant turn them off, for that we need a proper effect packet, as well as for it to work in multiplayer.
I based my work on master branch cause i had problems with /hax drive on dev
=> Vehicle destroy and damage levels, hax siren and headlights

src/servers/ZoneServer/commands/hax.ts, src/servers/ZoneServer/zonepackethandlers.ts, src/servers/ZoneServer/zoneserver.ts
Looks like i forgot to remove pos radius check on spawn props earlier, we spawn all props then there is no need to include them in client.spawnedEntities, No need to check prop characterId in remove out of dist since they arent there anymore.
=> Hotfix props & remove unnecessary checks

src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts
Second uint32 turned out to be objectId instead of the first one.
=> Updated DtoObjectInitialData

src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts
Packet "AcquaintanceAdd" adds a entry to "BaseClient.Acquaintances".
---------------------------------------------------------------------------------------
Fixed opcode and structure for reportreply packet. 
The first dword seems to be the typeId of report, available types are.
0 -  UI.ReportPlayer.Success
1 -  UI.ReportPlayer.Failure.PlayerNotFound
2 -  UI.ReportPlayer.Failure.RequestPending
4 -  UI.ReportPlayer.Failure.AlreadyReported
5 and above - UI.ReportPlayer.Failure.CampionWroteBadCode
---------------------------------------------------------------------------------------
**Ability.initAbility**
Reversed the initAbility packet, if first dword value is 3 the server sends the packet a second time?
Seems like the correct packet structure but packet aint doing that much? :O
=> Added missing packets

src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts, src/servers/ZoneServer/zoneserver.ts
Dont know if respawnLocations are used by the game, they are added to the datasource, but it seems that there is no way of using them.
RespawnReply packet wont do anything on its own, but it enables the loadingscreen preventing player from falling under map
=> Bugfix/:bug:enable loading screen on player respawn

src/servers/ZoneServer2016/managers/worldobjectmanager.ts, src/servers/ZoneServer2016/zoneserver.ts
We lowered number of loot at server start so calling it then is pointless, also should scale over time
=> Performance Improvements

src/servers/ZoneServer2016/data/Recipes.ts
Reported by "The Rizzler" on discord. Dressed bandage recipe didn't give back the bottle when crafted, in his words: "you're emptying the honey bottle onto the dressing so it's weird that the bottle would be consumed in the process." Fix: return an empty bottle lol
=> Dressed Bandage recipe

src/servers/ZoneServer2016/zoneserver.ts
Reported by Elypsia on discord, scarecrow masks weren't being counted as a helmet so add their description_id to the isHelmet function to fix this.
=> Fix scarecrow mask durability

src/servers/ZoneServer2016/entities/character.ts
Was reported by a user name Triggl/ Bornat on discord. The check for PvE doesn't occur until the damage function, so add a check before the bleeding code can occur to prevent players from killing each other due to bleeding.
=> Bugfix with melee bleeding on PvE

src/servers/ZoneServer2016/managers/gametimemanager.ts, src/servers/ZoneServer2016/zoneserver.ts
---
> ## TL;DR
> This pull request introduces changes to the `IngameTimeManager` class in the `gametimemanager.ts` file and the `ZoneServer2016` class in the `zoneserver.ts` file. The changes include the addition of a `nightMultiplier` property and a `getCycleSpeed` method to the `IngameTimeManager` class, and the replacement of the `cycleSpeed` calculation in the `sendGameTimeSync` method of the `ZoneServer2016` class with a call to the new `getCycleSpeed` method.
> 
> In the `IngameTimeManager` class, a `nightMultiplier` property was added to adjust the game time speed during night hours. The `getCycleSpeed` method was added to calculate the cycle …
=> speedup nights

src/protocols/lzconnectionprotocol.ts, src/servers/LoginServer/loginserver.ts
---
> ## TL;DR
> This pull request removes the "ClientBan" functionality from the `lzconnectionprotocol.ts` and `loginserver.ts` files. 
> 
> The "ClientBan" functionality was removed from the `lzconnectionprotocol.ts` file. This included removing the packet structure for "ClientBan" and the associated fields. 
> 
> In the `loginserver.ts` file, the case for "ClientBan" was removed from the switch statement. This included removing the logic for handling a "ClientBan" event, such as fetching the user session from the database and updating the banned light collection.
> 
> To test these changes, run the application and ensure that it still …
=> remove unused "clientban" lzprotocol packet

src/servers/ZoneServer2016/data/Recipes.ts, src/servers/ZoneServer2016/managers/craftmanager.ts, src/servers/ZoneServer2016/zoneserver.ts, src/types/zoneserver.ts
https://www.youtube.com/watch?v=aFpSNGow3QI
https://www.youtube.com/watch?v=DG7_CBDTsuM
https://www.youtube.com/watch?v=iQpJyKFLgnQ
I got my sources from these 3 videos, essentially ammo should require a weapon workbench to craft, and salvaging ammo shouldn't require a weapon workbench. In the first video, he is salvaging ammo inside of a bathroom, there's other parts of the video where he is salvaging ammo from file cabinets too, so this is more than enough to show that you don't need a weapon workbench for salvaging ammo. As for the weapon workbench crafting, https://survivorsrest.com/justsurvive/patchnotes the September 28th, 2016 update changed it so recipes that use gunpowder (ammo essentially), would require a weapon workbench for crafting, so add the logic for that and remove the …
=> Change salvaging ammo and update weapon workbench crafting

data/2016/sampleData/defaultconfig.yaml, src/servers/ZoneServer2016/managers/smeltingmanager.ts
https://www.youtube.com/watch?v=vpChC-4cKhE
Using this video as reference ^, furnaces in December 2016 used to smelt items in ~7 seconds, DBG also changed in the April 2016 update to where charcoal burns for 40 minutes rather than at the same speed as wood logs/planks etc. This PR changes the following:
- change smeltTime from 40 seconds to 7 seconds.
- add getBurnTime function to check if our current fuel item is charcoal or not, if so adjust the burnTime accordingly (40 mins for charcoal and 2 minutes for wood types)
- fix furnace sound bug where furnace noise would stop playing after the 1st item was done smelting.
- fix bee box fx (so bees fly around the bee box + noise)
=> CollectingEntity fixes

src/servers/GatewayServer/gatewayserver.threaded.ts, src/servers/GatewayServer/gatewayserver.ts, src/servers/ZoneServer2015/zoneserver.ts, src/servers/ZoneServer2016/zoneserver.ts
---
> 
> - Added a new method `getSoeClient` to `GatewayServerThreaded`
> - Modified the `getSoeClient` and `deleteSoeClient` methods in `GatewayServer`
> 
> 1. Run the application
> 2. Perform the actions that involve the `GatewayServerThreaded` and `GatewayServer` classes
> 3. Verify that the changes work as expected and do not introduce any issues
> 
> ## Why make this change
> - The addition of the `getSoeClient` method in `GatewayServerThreaded` allows retrieving a `SOEClient` object based on its ID
> - The modifications in the `getSoeClient` and `deleteSoeClient` methods in `GatewayServer` are made to use the corresponding methods …
=> Make some gatewayServer fields properly private

src/servers/GatewayServer/gatewayserver.threaded.ts, src/servers/GatewayServer/gatewayserver.worker.ts
---
> ## TL;DR
> This pull request makes changes to the `gatewayserver.threaded.ts` and `gatewayserver.worker.ts` files. It adds a new `clientInfoChannel` to the `GatewayServerThreaded` class and handles messages sent to this channel in the `gatewayserver.worker.ts` file. It also adds new methods to the `GatewayServerThreaded` class for retrieving information about a client and deletes a client.
> 
> - Added a new `clientInfoChannel` to the `GatewayServerThreaded` class.
> - Handled messages sent to the `clientInfoChannel` in the `gatewayserver.worker.ts` file.
> - Added new methods to the `GatewayServerThreaded` class for retrieving information about a …
=> Adapt GatewayServerThreaded to get clientinfo

data/2016/sampleData/defaultconfig.yaml, src/servers/ZoneServer2016/managers/configmanager.ts, src/servers/ZoneServer2016/managers/weathermanager.ts, src/servers/ZoneServer2016/models/config.ts
---
> ## TL;DR
> This pull request modifies the weather configuration in the game server. It changes the default weather template and introduces a new configuration option to enable or disable dynamic weather.
> 
> - The default weather template was changed from "z1br" to "h1emubaseweather" in the `defaultconfig.yaml` file.
> - A new configuration option `dynamicEnabled` was added to the `defaultconfig.yaml` file. This option allows the dynamic weather feature to be enabled or disabled.
> - The `ConfigManager` class was updated to read the `dynamicEnabled` option from the configuration file and set it in the `WeatherManager` class.
> - The …
=> Add enableDynamicWeather option to config file and change default weather to h1emubaseweather

src/servers/ZoneServer2016/managers/worldobjectmanager.ts
Maybe this is too much, but rn ppl don't play on low pop since the loot is so bad. I know we done that to avoid unemployed to have too much of an advantage but the fact is there is a lot of them. At the beginning of every wipe the server pop is always 40+ even at night, then these ppl have their bases and just stop playing and others who want to start the wipe mid train just can't due to low loot and that make a snowball and nobody play anymore.
=> Reduce spawn timer on low / medium pop

src/servers/ZoneServer2016/handlers/commands/dev.ts, src/servers/ZoneServer2016/managers/worldobjectmanager.ts
---
> ## TL;DR
> This pull request introduces a new feature to the `WorldObjectManager` class in the `ZoneServer2016` server. It adds a new static property `itemSpawnersChances` to keep track of the spawn chances of different items. It also adds a new command `sc` in the `dev` handler to log the `itemSpawnersChances`.
> 
> Two files were modified in this pull request:
> 
> 1. `src/servers/ZoneServer2016/handlers/commands/dev.ts`: A new command `sc` was added to the `dev` handler. This command logs the `itemSpawnersChances` from the `WorldObjectManager`.
> 
> 2. `src/servers/ZoneServer2016/managers/worldobjectmanager.ts`: A new static property …
=> Add dev command to list itemSpawners chances

src/servers/ZoneServer2016/zoneserver.ts
https://www.youtube.com/watch?v=aFpSNGow3QI (Timestamps: 18:22 | 18:51 | 21:33 | 23:30 | 25:09 | 57:06 - can show more proof if need be 👍 )
In #1777, avcio optimized getProximityItems so users can't proximity containers through base shelters (essentially esp), and just general code clean-up. Wonderful change! But in the process made it so world lootable props (armoires, cabinets, fridges etc.) had to be searched through at least once before you could proximity them. In december 2016 this wasn't a thing however. You could proximity world lootable props no matter what, so this PR aims to remove that restriction WHILE keeping avcios wonderful change from before :D
=> Add proximityItems without having to search first

src/servers/ZoneServer2016/classes/collectingentity.ts, src/servers/ZoneServer2016/classes/smeltingentity.ts
This way we could save constructions data to mongo more efficiently without needing all the processing we currently do to setup save objects. #1798
---
> ## TL;DR
> This pull request refactors the `CollectingEntity` and `SmeltingEntity` classes in the `ZoneServer2016` server. The `parentObject` property, which was previously of type `LootableConstructionEntity`, has been replaced with `parentObjectCharacterId` of type `string`. This change simplifies the code .
> 
> In both `CollectingEntity` and `SmeltingEntity` classes, the `parentObject` property has been replaced with `parentObjectCharacterId`. All references to `this.parentObject` have been updated …
=> Remove circular dependencies in Collecting and Smelting entitiesingentity.ts

data/2016/dataSources/HudIndicators.json, src/servers/ZoneServer2016/classes/collectingentity.ts, src/servers/ZoneServer2016/entities/character.ts, src/servers/ZoneServer2016/entities/lootableconstructionentity.ts, src/servers/ZoneServer2016/managers/smeltingmanager.ts
https://www.youtube.com/watch?v=-ay3Osxv3Zc&t=158s
People (JayR and Statix) were losing their minds over the bee fx change and their bee boxes always buzzing with bees 😂😂 A quote from JayR directly: "all bee boxes have loud ass bees in them, i play muted now" 🤣 So this PR changes the bee fx to only occur when a honeycomb spawns and when a honeycomb is currently inside of the bee box (to alert players to loot their bee box for their honeycomb!) 
Also added some type safety stuff, bee retaliation damage hudindicator, and fx
=> change bee fx and add bee retaliation hudindicator, damage and fx

src/servers/ZoneServer2016/data/lootspawns.ts
---
> ## TL;DR
> This pull request modifies the loot spawn chances and items in the "Cabinets Cube" section of the `lootspawns.ts` file. The spawn chance has been reduced from 100 to 80, and several canned food items have been removed from the loot spawn list.
> 
> The spawn chance for the "Cabinets Cube" section has been reduced from 100 to 80. This means that there is now a 20% chance that no loot will spawn in these cabinets.
> 
> Additionally, a large number of canned food items have been removed from the loot spawn list for these cabinets. 
> 
> To test these changes, you can spawn in a zone with "Cabinets Cube" and observe the loot …
=> Update Cabinet Cube spawn table

src/servers/ZoneServer2016/classes/zoneclient.ts, src/servers/ZoneServer2016/zoneserver.ts
---
> # Pull Request Description
> 
> ## TL;DR
> This pull request includes changes to the `ZoneServer2016` and `ZoneClient2016` classes. It primarily focuses on the handling of the `hudTimer` property, ensuring that it is properly initialized and reset when necessary.
> 
> - In `zoneclient.ts`, the `hudTimer` property is now initialized to `null`.
> - In `zoneserver.ts`, additional checks and actions have been added to the `stopHudTimer` method. If the `hudTimer` is `null`, the method will return early. After the timer is utilized, it is reset to `null`.
> - The `utilizeHudTimer` method in `zoneserver.ts` has also been updated to reset the `hudTimer` to …
=> Fix StartTimer packet being sent at every weapon fire

src/servers/ZoneServer2016/managers/constructionmanager.ts
In #1387, Avcio disable punji's inside of POIs (I'm assuming because they can't be broken and cause clutter) and people are doing the same with snares from what I've noticed (same issue you can't melee/shoot or break snares in any way), so disable their POI placement.
=> disable snare poi placement

src/servers/ZoneServer2016/entities/vehicle.ts
---
> ## TL;DR
> This pull request introduces a change in the `vehicle.ts` file to prevent damage to vehicles in PvE (Player versus Environment) mode. 
> 
> A new condition was added in the `damage` function of the `Vehicle2016` class. This condition checks if the server is in PvE mode and if the `damageInfo` object has an `entity` property. If both conditions are met, the function returns immediately, preventing any further execution and thus any damage to the vehicle.
> 
> Here is the added line of code:
> ```javascript
> if (server.isPvE && damageInfo.entity) return;
> ```
> 
> To test this change, follow these steps:
> 
> 1. Start …
=> Fix vehicle that could be destroyed in PVE

src/servers/ZoneServer2016/managers/smeltingmanager.ts
Okay, so several people are reporting that furnaces are still messed up, so for now just deprecate the recent furnace change to burnTime (keep smeltTime that shouldn't be causing issues) until more testing can be done.
=> Deprecate furnace change

src/servers/ZoneServer2016/entities/vehicle.test.ts
---
> ## TL;DR
> This pull request introduces tests for the `Vehicle2016` class in the `ZoneServer2016` module. The tests cover damage handling in both PvE and PvP scenarios, including damage from entities and collisions.
> 
> A new test file `vehicle.test.ts` was added to the `ZoneServer2016/entities` directory. This file contains two main tests: `Damage-pve` and `Damage-pvp`. Each test creates a new instance of `ZoneServer2016` and `Vehicle2016`, and then tests the `damage` method of the `Vehicle2016` class under different conditions.
> 
> To run the tests, navigate to the project root directory and run the command `npm test`. Ensure …
=> Add vehicles damage unit tests for PVP&PVE

src/servers/ZoneServer2016/entities/vehicle.test.ts, src/servers/ZoneServer2016/entities/vehicle.ts
in #1892, kentin implemented a fix for being able to shoot cars on PvE. This unintentionally stopped vehicle decay and wrenches from working on PvE, so revert that change and add OnProjectileHit for the vehicle class, and check in there.
=> Fix for wrench, car decay, and players shooting cars on PvE

src/servers/ZoneServer2016/zoneserver.ts
---
> ## TL;DR
> This pull request introduces a check for unknown HUD indicators in the `ZoneServer2016` class. If an unknown HUD indicator is found, it is removed and a console log is generated for debugging purposes.
> 
> The `forEach` loop that iterates over `client.character.resourceHudIndicators` now includes a check for unknown HUD indicators. If an unknown indicator is found, it is removed from the `resourceHudIndicators` array and a console log is generated with the name of the unknown indicator. 
> 
> To test this change, you can add an unknown HUD indicator to the `resourceHudIndicators` array of a character and observe the …
=> Handle unknown HudIndicator

data/2016/sampleData/defaultconfig.yaml, src/servers/ZoneServer2016/handlers/commands/commands.ts, src/servers/ZoneServer2016/managers/configmanager.ts, src/servers/ZoneServer2016/managers/gametimemanager.ts, src/servers/ZoneServer2016/managers/weathermanager.ts, src/servers/ZoneServer2016/models/config.ts, src/servers/ZoneServer2016/zoneserver.ts
---
> ## TL;DR
> This pull request updates the game time management system to include new configurations for time freezing, night time multiplier, base time, and time multiplier.
> 
> - Added new configurations for game time management in the `defaultconfig.yaml` file.
> - Updated the `commands.ts` file to reflect changes in the time multiplier command.
> - Modified the `configmanager.ts` file to handle new game time configurations.
> - Updated the `gametimemanager.ts` file to incorporate the new time management settings.
> - Adjusted the `weathermanager.ts` file to use the base time multiplier for weather updates.
> - Added a new `GameTimeConfig` …
=> Add ingameTime fields in config

src/servers/ZoneServer2016/managers/worlddatamanager.test.ts
---
> ## TL;DR
> This pull request fixes the issue where the order of loaded constructions was not consistent due to MongoDB's handling of data. It introduces a sorting mechanism based on the characterId to ensure the order is consistent.
> 
> The main change is in the `worldSaveUnitTests` function in the `worlddatamanager.test.ts` file. After loading the constructions, they are now sorted by `characterId` before being compared for equality. This ensures that the order of constructions is consistent, regardless of how MongoDB returns the data.
> 
> To test this change, run the unit tests for the `worlddatamanager.test.ts` file. The test …
=> Fix load construction unit test

src/servers/ZoneServer2016/entities/vehicle.ts
In the September 28th, 2016 update, DBG added vehicle keys to cars. In this update, they also made it so vehicle keys can bypass hotwiring if: the driver has a key, the vehicles inventory has a key, or if any of the passengers have a key. This PR is to reflect the last change in particular, allowing any passenger with a vehicle key to bypass the hotwire function of the car. Also added the model for vehicle keys when dropped.
This PR changes - 
- Allows vehicle hotwire to be bypassed if any of the passengers have a vehicle key.
- Add model for vehicle key on drop
Known issue:
Not really an issue, but when a the driver doesn't have a key, but the passengers do, users will still get the alert "you must have a vehicle key or hotwire to operate". I believe it's some kind of built in H1Z1 …
=> Passenger Vehicle Keys

data/2016/sampleData/defaultconfig.yaml, src/servers/ZoneServer2016/managers/configmanager.ts, src/servers/ZoneServer2016/managers/constructionmanager.ts, src/servers/ZoneServer2016/models/config.ts, src/servers/ZoneServer2016/zoneserver.ts
So something that I remembered from 2016 was the "restricted building" ruleset image on the server select screen that basically told you if a server allowed you to build in pois or not. I miss the hammer and triangle picture so this is something I've tried to work on for a while but finally managed to get working 😂 I found it from decompiling the CharacterSelect.gfx actionscript file, there were some other gamemodes included in there too!
So this PR: 
- Adds restricted building ruleset & image to server select screen
- Add isNoBuildInPois config variable for building in poi and removed allowPOIPlacement
=> Add restricted building rulesets

src/servers/ZoneServer2016/entities/vehicle.ts, src/servers/ZoneServer2016/models/enums.ts, src/servers/ZoneServer2016/zoneserver.ts
In the July 7th, 2016 update facepunch added Anti-Vehicle hoarding measures to prevent players from excessively storing cars.  Currently on H1EMU, wrenches have 2k durability and repair the vehicle 5% per swing for a maximum of 100%. In the Anti-Hoarding update, wrenches had 2.5k durability and repaired the vehicle by 2% per swing for a maximum of 50%. This PR is to make the wrench more in-line with that update.
This PR changes - 
- Modified wrench to have 2.5k durability and repair a vehicle by 2% per swing
- Fixed a bug where you couldn't refuel a vehicle if the fuel amount was between 76-99%.
=> Make wrench consistent with July 2016 update

src/servers/ZoneServer2016/zonepackethandlers.ts
So when you try to add someone to permissions on a foundation type, the characters name you enter is case sensitive and also doesn't work for offline players.
This PR changes - 
- NpcFoundationPermissionsManagerAddPermission to allow offline characters to be added and non case sensitivity names to be permitted. 
I've been struggling to get mongodb to work so I wasn't able to test if getOfflineClientByName works, but I based my logic upon the whisper command which does work (as far as I'm aware).
=> Optimize NpcFoundationPermissionsManagerAddPermission

src/servers/SoeServer/soeserver.ts
---
> ## TL;DR
> This pull request modifies the SOEServer class to improve packet handling. It changes the way packets are resent and how unacknowledged data is stored.
> 
> The main changes are in the `SOEServer` class. 
> 
> 1. The condition for resending packets has been updated. Previously, a packet was resent if its timestamp plus the resend timeout and the client's average ping was less than the current time. Now, an additional wait time (`this._waitTimeMs`) is added to the condition.
> 
> 2. The way unacknowledged data is stored has been simplified. Previously, the timestamp when the data was stored was added to the current time plus a wait time. …
=> Properly calculate ping

src/servers/ZoneServer2016/handlers/commands/dev.ts
---
> ## TL;DR
> This pull request introduces a new `lag` command in the `dev.ts` file. This command is designed to simulate lag in the server for testing purposes.
> 
> A new function named `lag` was added to the `dev.ts` file. This function uses a `setInterval` to create a loop that runs a billion times, effectively simulating lag on the server.
> 
> ```javascript
> lag: function (server: ZoneServer2016, client: Client, args: Array<string>) {
>   setInterval(() => {
>     for (let i = 0; i < 1_000_000_000; i++) {
>       // do nothing but hold the event loop
>       const a = i;
>       a;
>     }
>   }, 0);
> },
> ```
> 
> To test …
=> Add /dev lag to simulate high load

src/servers/GatewayServer/gatewayserver.ts, src/servers/SoeServer/soeserver.ts, src/servers/ZoneServer2016/handlers/commands/commands.ts
---
> ## TL;DR
> This pull request introduces a new feature to monitor server lag and network statistics. It also modifies the existing commands to include these new stats.
> 
> - Added a new method `getServerNetworkStats` in `GatewayServer` to fetch server network statistics.
> - In `SOEServer`, added properties to track event loop lag and calculate average lag. Also, added a new method `getNetworkStats` to return server lag.
> - Modified the existing commands in `ZoneServer2016` to include server stats along with client stats.
> 
> - After pulling the changes, start the server and connect a client.
> - Use the modified commands to …
=> Remove server lag from ping calculation

src/servers/SoeServer/soeserver.ts
---
> ## TL;DR
> This pull request modifies the `SOEServer` class to improve the calculation of average server lag and the handling of "Ack" packets.
> 
> Two main changes were made in the `soeserver.ts` file:
> 
> 1. In the `getNetworkStats` method, the calculation of `avgServerLag` was modified. Now, if `this.avgEventLoopLag` is less than or equal to 1, `avgServerLag` is set to 0. This prevents negative values for server lag.
> 
> 2. In the handling of "Ack" packets, a new variable `currentLag` was introduced. This variable is set to `this.currentEventLoopLag` or 0 if `this.currentEventLoopLag` is undefined. This change ensures that `currentLag` is …
=> Unallow server lag to be negative

src/servers/SoeServer/soeserver.ts
---
> # Pull Request Description
> 
> ## TL;DR
> This pull request modifies the `SOEServer` class to improve the calculation of event loop lag. It introduces a constant interval time and adjusts the calculation of the current event loop lag.
> 
> The main changes are in the `SOEServer` class in the `soeserver.ts` file. 
> 
> - A constant `intervalTime` of 100 was introduced.
> - The calculation of `this.currentEventLoopLag` was adjusted to subtract `intervalTime` from the floor value of `entry.duration`.
> - The interval for the performance measurement was changed from 0 to 100.
> 
> ```diff
> +      const intervalTime = 100;
>        const obs = new …
```
=> Reduce serverLag calculation cpu usage

src/servers/ZoneServer2016/handlers/commands/dev.ts
---
> ## TL;DR
> This pull request introduces a change to the `lag` function in the `dev.ts` file. The change ensures that the function only runs for a maximum of 20 seconds.
> 
> The `lag` function was previously set to run indefinitely. This change introduces a time limit to the function. The function now checks the elapsed time since it started running and stops after 20 seconds.
> 
> ```diff
> - setInterval(() => {
> + const startTime = Date.now();
> + const interval = setInterval(() => {
> +   if (Date.now() - startTime > 20000) {
> +     clearInterval(interval);
> +   }
> ```
> 
> To test this change, you can call the `lag` …
=> Make /dev lag ending artificial lag after 20seconds

src/servers/ZoneServer2016/entities/trapentity.ts
#1988 was nice that the logic already existed for it 😅 was just never implemented.
This PR makes:
- World spawned trap entities not be able to receive damage
=> TrapEntity damage

src/servers/ZoneServer2016/managers/constructionmanager.ts
Title ^ my dumbass accidentally did if (server.isNoBuildInPois) instead of (!server.isnoBuildInPOIs) 😭
While I was at it I moved the !server.isNoBuildInPois into the detectPoiPlacement where allowPoiPlacement was originally
=> Fix isNoBuildInPOIs boolean algebra

src/servers/ZoneServer2016/entities/character.ts
Someone did this to me on wipe, super cringe stuff (sadly AMD didn't clip it, I wish it did). Essentially while a player is respawning, you can melee their corpse and when the player respawns, they will be low hp or nearly dead.. So this PR fixes that by adding checks to the OnMeleeHit and Damage functions in the character class to see if a player is currently respawning
=> Fix melee damage while respawning

src/servers/ZoneServer2016/zoneserver.ts
#1979, when the resourceids.fuel + fuelValue is over or equal to 10000, adjust the fuel level to be 10000 to prevent the fuel resource from being broken
=> Allow refueling to 100, but not exceed

data/2016/sampleData/defaultconfig.yaml
So to follow-up with #1972, in the same screenshot DBG talks about how they lowered vehicle decay to quote: "decay their condition slowly over time. they [vehicles] will fully decay in a little over two days." 
This PR lowers the baseVehicleDamage to be 2000 which is a little over two days (50 hours to be exact). 
In my personal opinion too, I think vehicle decay was a little too quick before also. It was around ~15 hours even if you only had 1 car and it was full hp! Also I was wondering to maybe buff maxVehiclesPerArea by 1? If I'm not mistaken, in 2016 you could have 3 cars but once you had 4 then the vehicle decay would ramp up, but I could be remembering wrong
=> Lower vehicle decay rate

src/servers/ZoneServer2016/entities/character.ts, src/servers/ZoneServer2016/managers/constructionmanager.ts, src/servers/ZoneServer2016/zoneserver.ts
https://www.youtube.com/watch?v=WpSL7cDjQRs&t=429s (3:05, other parts of the vids he shows him hammering too)
So currently, a common thing players like to do when getting raided is to have multiple people melee spamming hammers on the base so explosives like ethanol/biofuel have less of a chance to destroy the construction - not a problem with IEDs b/c you can light multiple of them at once (the math to determine if a construction will be repaired or not while in the middle of exploding is completely random, it's based upon timing, server lag, whole bunch of other shit etc.) 
Anyways, this is super boring gameplay to just have people sitting there spamming to repair the base than actually defending it... So this PR adds a 1 second delay between repair times to prevent this kind of …
=> Hammer cooldown for repairing constructions

src/servers/ZoneServer2016/entities/basefullcharacter.ts, src/servers/ZoneServer2016/entities/character.ts, src/servers/ZoneServer2016/entities/npc.ts, src/servers/ZoneServer2016/entities/vehicle.ts, src/servers/ZoneServer2016/zoneserver.ts
Fix for #1995 and #1990, I'm pretty sure changing the ITEM_TYPE on an item will cause crashes for some odd reason (possible built in H1Z1 function that checks for validity or something). Should be good now though 👍
=> Fix skinning knife durability/damage

src/servers/ZoneServer2016/entities/character.ts, src/servers/ZoneServer2016/managers/craftmanager.ts, src/servers/ZoneServer2016/zoneserver.ts
---
> ### TL;DR
> This pull request updates the `Character2016` class to include a `recipes` property and a `pGetRecipes` method, moves recipe handling from `ZoneServer2016` to `Character2016`, and updates `CraftManager` to use character recipes instead of server recipes.
> 
> ### What changed
> - Added a `recipes` property to the `Character2016` class to store all recipes on a server.
> - Implemented a `pGetRecipes` method in the `Character2016` class to retrieve recipes based on the server.
> - Updated `CraftManager` to use character recipes (`client.character.recipes`) instead of server recipes (`server._recipes`).
> 
> ### How to test
> 1. Ensure the `Character2016` …
=> Recipe system rework

src/servers/ZoneServer2016/handlers/commands/commands.ts
---
> ## TL;DR
> This pull request modifies the way server uptime is calculated in the `commands.ts` file of the `ZoneServer2016` module. Instead of using a custom function, it now uses Node.js's built-in `process.uptime()` function.
> 
> The line of code that calculates the server's uptime in minutes was changed. Previously, it was using a function called `getCurrentServerTimeWrapper().getMinutes()`. Now, it uses `process.uptime() / 60`.
> 
> ```diff
> - const uptimeMin = getCurrentServerTimeWrapper().getMinutes();
> + const uptimeMin = process.uptime() / 60;
> ```
> 
> To test this change, you can run the server and use the command …
=> Use process.uptime

src/servers/ZoneServer2016/handlers/commands/commands.ts
---
> ## TL;DR
> This pull request adds a new feature to the server command handler that allows it to count and display the number of destroyable objects in the game.
> 
> A new line of code was added to the server command handler in the `commands.ts` file. This line of code counts the number of destroyable objects (dto) and sends this information as a chat text to the client.
> 
> To test this change, you can use the server command handler to request the number of destroyable objects. The server should respond with a chat text displaying the number of these objects.
> 
> ## Why make this change
> This change was made to provide more …
=> o number of dto to serverinfO

src/servers/ZoneServer2016/managers/worldobjectmanager.ts
---
> ## TL;DR
> This pull request modifies the `WorldObjectManager` class in the `ZoneServer2016` server to generate a transient ID for interaction replication when creating `Crate` and `Destroyable` objects.
> 
> The `WorldObjectManager` class was previously using a hardcoded value of `1` for the transient ID when creating `Crate` and `Destroyable` objects. This pull request changes this to use the `getTransientId` method of the `server` object, passing in the `characterId` as an argument.
> 
> To test this change, you can create `Crate` and `Destroyable` objects in the `ZoneServer2016` server and check that the transient ID is …
=> Give proper transientId to destroyables

src/servers/ZoneServer2016/entities/destroyable.ts
---
<details open><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request introduces a temporary hack to prevent certain models from being destroyed by setting their maximum health to the maximum value of a 32-bit unsigned integer.
> 
> The maximum health for the following models: `FENCES_WOOD_PLANKS_GREY_1X1`, `FENCES_WOOD_PLANKS_GREY_POSTS_1X2`, and `FENCES_WOOD_PLANKS_GREY_GAP_1X1` has been changed from `7500` to `MAX_UINT32` (the maximum value of a 32-bit unsigned integer). This change effectively makes these models indestructible, unless you really want to destroy them.
> 
> To test this change, you can try to destroy the aforementioned models in the game. You should find that …
=> Disable the destruction of glitched wood fences

src/servers/ZoneServer2016/handlers/commands/commandhandler.ts
---
<details open><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request refactors the `executeCommand` method in the `CommandHandler` class. It improves the handling of command arguments and adds type checking for the packet parameter.
> 
> The `executeCommand` method now checks if the `hash` and `arguments` properties exist in the `packet.data` object before proceeding. This prevents potential runtime errors when these properties are undefined. 
> 
> The `packet` parameter's type has been changed to `ReceivedPacket<CommandExecuteCommand>`, providing better type safety.
> 
> The `args` variable is now declared with `let` and is assigned an empty array if `packet.data.arguments` is undefined. This …
=> Add some type safety to commandHandler

src/servers/ZoneServer2016/managers/pluginmanager.ts, src/servers/ZoneServer2016/zonepackethandlers.ts, src/servers/ZoneServer2016/zoneserver.ts
---
<details open><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request updates the `PluginManager` and `ZonePacketHandlers` classes in the `ZoneServer2016` project to use the `server.commandHandler` instead of `this.commandHandler`.
> 
> - Updated the `PluginManager` class to use `server.commandHandler` instead of `this.commandHandler`.
> - Updated the `ZonePacketHandlers` class to use `server.commandHandler` instead of `this.commandHandler`.
> - Added a new import statement for `CommandHandler` in `zoneserver.ts`.
> - Added a new method `reloadCommandCache` in `ZoneServer2016` to reload the command cache.
> 
> 1. Pull the changes from this branch.
> 2. Run the application.
> 3. …
=> Move commandHandler to zoneserver

src/servers/ZoneServer2016/handlers/commands/commandhandler.ts
---
<details open><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request fixes a case sensitivity issue in the `commandhandler.ts` file. The file name `internalCommands` has been changed to `internalcommands` to match the actual file name.
> 
> In the `commandhandler.ts` file, the `require.resolve` method was previously trying to resolve `./internalCommands`, which does not exist. This has been corrected to `./internalcommands`.
> 
> To test this change, you can try to run the `reloadCommands` function in the `CommandHandler` class. If the function runs without any errors, it means that the `require.resolve` method is now correctly resolving the `internalcommands` file.
> 
> ## Why …
=> Fix an issue while reloading commands

src/servers/ZoneServer2016/managers/smeltingmanager.ts
Was reported by [GER]Frank on discord.
Was a slight oversight from #2006. This PR just adds a check to see if the entity is a bee box, if so to proceed with that set of checks and if not to proceed with the rest of the code.
Also noticed some typos for documentation in the SmeltingManager class so fixed that up to :D
=> fix for dew collector not working

src/servers/ZoneServer2016/entities/basefullcharacter.ts, src/servers/ZoneServer2016/zonepackethandlers.ts
Refactored `lootAccountItem` method to handle optional items and updated zone packet handlers to use this method with timeout adjustments.
- Modified `lootAccountItem` method in `BaseFullCharacter` to handle optional `item` parameter and return early if the item is not provided.
- Updated `zonepackethandlers.ts` to replace `lootItem` with `lootAccountItem` and introduced a 12-second timeout before calling the method.
1. Run the server and ensure that the changes do not introduce any runtime errors.
2. Test looting functionality in various scenarios to ensure the method handles optional items correctly.
2. Verify timeout handling in the looting process.
This change was made to improve the robustness of the looting functionality by ensuring that it can handle cases where no item is …
=> Display reward notification after case unboxing

src/servers/ZoneServer2016/entities/character.ts, src/servers/ZoneServer2016/managers/playtimemanager.test.ts, src/servers/ZoneServer2016/managers/playtimemanager.ts, src/servers/ZoneServer2016/managers/worlddatamanager.ts, src/servers/ZoneServer2016/zoneserver.ts, src/types/savedata.ts
This PR introduces a new PlayTimeManager to track the playtime for characters. It includes changes to character entities, the world data manager, and the zone server to support playtime tracking. Additionally, it adds unit tests to ensure the PlayTimeManager works correctly with and without MongoDB. The changes also update the character save and load methods to include playtime.
---
=> Add playtime manager

src/servers/ZoneServer2016/managers/worlddatamanager.ts
Simplifies promise handling in the saveCharacterData loop by removing unnecessary wrapping.
The promise handling in the saveCharacterData loop was simplified by directly pushing the promise returned by saveCharacterData into the promises array, instead of wrapping it in a then block.
The change does not alter the behavior of the code. However, to ensure everything is working correctly, run the existing tests and verify that all functionalities related to saving character data are operating as expected.
The change was made to simplify the code. Unwrapping the promise handling makes the code easier to read and maintain without affecting its functionality.
---
=> Change weird syntax in character save

package-lock.json, package.json
Update dependencies in the package.json and package-lock.json. Upgrades included: 'h1z1-dataschema' from 1.7.1 to 1.7.2, replaces 'ip' with 'ip-address' version 9.0.5, upgrades 'socks' from 2.7.1 to 2.8.3, added new dependencies 'jsbn' version 1.1.0 and 'sprintf-js' version 1.1.3.
---
=> Update h1z1-dataschema version

.github/workflows/dev-test.yml, .github/workflows/release.yml, package.json, src/servers/LoginZoneConnection/shared/baselzconnection.ts, src/servers/ZoneServer2016/managers/configmanager.ts, src/servers/ZoneServer2016/zoneserver.ts
pkg is old now and doesn't support node >18 and was pretty much garbage. we will use https://nodejs.org/docs/latest/api/single-executable-applications.html when it's ready
=> remove binaries building

src/servers/SoeServer/soeclient.ts, src/servers/SoeServer/soeserver.test.ts, src/servers/SoeServer/soeserver.ts, src/servers/ZoneServer2016/zonepackethandlers.ts
- **reorganise stuff around soeclientid**
- **only add char to h1emu-ai if in solomode or enabled**
- **rm unused import**
- **force-close sendingprocess when the client is deleted**
=> fix mem leak soe

src/servers/ZoneServer2016/data/lootspawns.ts
https://www.youtube.com/watch?v=aSiOyJaMd4c
https://www.youtube.com/watch?v=Yzmb_plgkus
https://www.youtube.com/watch?v=LxzQ96HI5sM
https://www.reddit.com/r/h1z1/comments/4x2x4z/just_survive_loot/
Used these sources as well as some of my old knowledge from playing the old H1Z1 in 2016. The 1000 backpacks should be more rare than they are now. You can confidently find one majority of the time, but that wasn't common in 2016. I vividly remember players would use framed backpacks as their main backpack source, not the blue and orange that is common now.
This values felt decent, but could be nerfed more
=> Lower 1000 bulk backpack spawns

src/servers/ZoneServer2016/models/enums.ts
Reported by: Wxlmart in the discord
Orange backpack model 1355 has several bugs to it, never use it (prob some old shit dbg was too lazy to remove) 
Changed the model to 2116 which has no bugs, current bulk, and can be skinned.
=> Fix orange backpack bulk & not skinnable issue

src/servers/ZoneServer2016/models/enums.ts
Didn't realize when pushing #2401 that the white helmet is messed up too. When you equip it, the skin is light red, so disable it until it's fixed (also didn't have a world model, so added that)
=> Fix and disable white motorcycle helmet

src/servers/ZoneServer2016/zonepackethandlers.ts
So from testing, Vehicle Collision packets get sent very frequently when off-roading (depending on vehicle type), and with the change in #2394, these tend to snowball pretty quick. From testing, damage <= 100 got rid of the smaller damage values that get sent when off-roading
=> Fix for vehicle collision dmg on small bumps

src/protocols/h1z1protocol.ts
Added support for packet opcode 0xce in H1Z1 protocol
Added a new case handler for opcode 0xce in the H1Z1Protocol class with an offset of 3 bytes
1. Run the game client
2. Verify packets with opcode 0xce are properly handled
3. Check logs to ensure no unknown packet errors for 0xce
This addition enables proper handling of a previously unsupported packet type, preventing it from falling through to the default error case and improving protocol compatibility
=> Fix shortcircuit log for ragdolls

src/servers/ZoneServer2016/zoneserver.ts
Skinning conveys the durability is 0, this fix the issue but may have to be rework later on
=> fix Skinned convey

src/packets/ClientProtocol/ClientProtocol_1080/shared.ts, src/servers/ZoneServer2016/entities/npc.ts, src/servers/ZoneServer2016/zoneserver.ts
Renamed `unknown6` to `flag` in death packet data and added TypeScript interface for better type safety.
- Created new `MultiDeathData` interface to define the structure of death packet data
- Renamed the ambiguous `unknown6` parameter to more descriptive `flag` in both shared protocol and NPC entity code
- Updated references to use the new interface and parameter name
1. Kill an NPC in-game
2. Verify death animations still trigger correctly
3. Check both ragdoll (flag=128) and non-ragdoll (flag=0) death states work as expected
Improves code readability and maintainability by:
- Providing clear type definitions for death packet data
- Using more meaningful parameter names that better describe their purpose
- Making the relationship between the flag value and ragdoll behavior more explicit
=> Creating typing for multideath

src/packets/ClientProtocol/ClientProtocol_1080/shared.ts
Improved death animation packet handling by introducing proper typing and more efficient character ID processing
- Added `MultiDeathData` interface to properly type death animation data
- Replaced manual character ID parsing with `BigInt` operations
- Renamed `unknown6` parameter to more descriptive `flag`
- Updated NPC death handling to use the new flag parameter name
1. Kill NPCs in-game
2. Verify death animations still work correctly
3. Check both ragdoll (flag = 128) and non-ragdoll (flag = 0) death animations
The previous implementation used unclear parameter names and inefficient character ID parsing. This change improves code readability and maintainability while potentially offering better performance through the use of native BigInt operations.
=> Use bigints to write characterIds in custom pack

src/servers/ZoneServer2016/zoneserver.ts
Currently startedSurvivingTP will display times during when the player was logged off, leading to bigger than intended times. This PR fixes that by "shifting" the time to prevent offline time being tracked in startedSurvivingTP
=> Fix metric survive time

src/servers/ZoneServer2016/zoneserver.ts
So currently when you have a construction item in your inventory (gate, shelter, foundation etc). It has 2000 durability, but it shouldn't have any at all. This also gets applied to things like wheat/corn seeds too. 
No, this doesn't affect raiding durability - I made sure to test for that lol
=> Fix construction items having durability

src/servers/ZoneServer2016/data/lootspawns.ts
https://www.youtube.com/watch?v=BeYQNMiKuO8 22:25 | 23:00 
Tan military backpacks used to spawn in the world just like 1000 bulk backpacks do now. Wasn't sure on weight amount, so I did 25 so it's 20% to spawn if spawnChance has been triggered.
=> add tan mil to world spawns

src/servers/ZoneServer2016/managers/worlddatamanager.ts, src/types/savedata.ts
Removed unused `groupId` field from character save data
- Removed `groupId` field from character save data interfaces and related code
- Eliminated commented-out `groupId` assignments in the `WorldDataManager`
1. Load an existing character
2. Verify character data loads correctly without errors
3. Save character data and confirm it persists properly
4. Check that group functionality continues to work as expected
The `groupId` field was not being actively used in the codebase and was only present as commented-out code. Removing it helps maintain cleaner data structures and eliminates unused fields from the save data.
=> remove saving of groupid

src/servers/ZoneServer2016/managers/groupmanager.ts, src/servers/ZoneServer2016/zoneserver.ts
Added functionality to retrieve and restore a player's group membership when logging in.
- Added a new `getGroupId` method to the GroupManager class that queries the database for a player's group membership
- Modified character loading to restore the player's group ID from the database instead of defaulting to 0
1. Create a group with multiple players
2. Have one player log out
3. When they log back in, verify they are still part of the same group
4. Test in both solo and multiplayer modes to ensure proper behavior
Players were losing their group membership upon logging out and back in, as the group ID was being reset to 0. This change maintains group persistence across login sessions, improving the multiplayer experience.
=> get group id from /groups collection directly

src/servers/ZoneServer2016/managers/smeltingmanager.ts, src/servers/ZoneServer2016/managers/weathermanager.ts, src/servers/ZoneServer2016/zoneserver.ts
Added functionality to automatically fill dew collectors with water when it rains.
It fill up to 6 bottle per ingame hour of raining.
- Added a new `fillDewCollector` method to the `SmeltingManager` class
- Extended `WeatherManager` to emit a "raining" event when rain starts
- Connected the weather and smelting managers in `ZoneServer` to trigger dew collector filling when it rains
1. Place a dew collector in the game world
2. Add empty water bottles to the collector's inventory
3. Wait for rain to start
4. Verify that empty water bottles are automatically converted to filled water bottles
To automate the dew collector functionality, making it more realistic and convenient for players by automatically collecting water during rainfall instead of requiring manual interaction.
=> fill dew collectors while raining

src/servers/ZoneServer2016/managers/weathermanager.ts
Fixed rain bottle collection to trigger once per rain hour instead of continuously.
Added a `lastRainingHour` tracking variable to ensure the "raining" event only emits once per hour during rainy periods. Previously, the event would emit continuously while it was raining, leading to potential issues with rain bottle collection.
1. Enter a zone during rainy weather
2. Verify that rain bottles can only be collected once per hour
3. Confirm that rain bottles reset properly when moving to a new hour
4. Check that rain state properly resets when leaving rainy periods
The previous implementation allowed for continuous rain bottle collection during rainy hours, which wasn't the intended behavior. This change ensures players can only collect one rain bottle per hour during rainy periods, …
=> fill one bottle per hour raining

src/servers/ZoneServer2016/zoneserver.ts
Removed the `sourceIsProjectile` check that was preventing projectiles from damaging bases. This allows all damage sources, including projectiles, to affect base structures and trigger explosive chain reactions.
1. Join a server
2. Create a base structure
3. Fire projectiles at the base
4. Verify that projectiles now cause damage to the base structures
5. Test with explosive objects to ensure chain reactions still work as expected
=> authorize explosion damages from projectiles

src/servers/ZoneServer2016/entities/destroyable.ts
Added explosive damage handling to destroyable entities
Added a new `OnExplosiveHit` method to the Destroyable class that allows destroyable objects to take damage from explosive sources within a 5-unit radius. When hit, the object takes damage equal to its full health, effectively destroying it.
1. Place a destroyable object in the game world
2. Trigger an explosive effect near the object (within 5 units)
3. Verify that the object is destroyed when within range
4. Verify that objects outside the 5-unit radius remain intact
To implement proper interaction between explosives and destructible objects in the game world, creating more dynamic and realistic environmental destruction mechanics.
=> DTO explosive damages

src/servers/ZoneServer2016/managers/groupmanager.ts
Removed group leader validation check when inviting players to a group
Commented out the code block that validates whether a player is the group leader before allowing them to send group invites
1. Join a group as a non-leader member
2. Attempt to invite another player to the group
3. Verify that you can now send invites regardless of leader status
To allow all group members to invite other players to their group, rather than restricting this functionality to only the group leader. This creates a more collaborative group management experience.
=> Allow every members of a group to invite new ones

src/servers/ZoneServer2016/zoneserver.ts
Refactored kill feed notification logic to use existing helper method for broadcasting death messages.
Replaced manual client iteration and POI checking with `sendDataToAllWithSpawnedEntity` helper method when sending kill feed notifications. Removed redundant POI check and simplified the conditional logic.
1. Join a game with multiple players
2. Kill another player
3. Verify that kill feed notifications appear correctly for all relevant players
4. Verify that suicide attempts don't trigger kill feed messages
The existing helper method `sendDataToAllWithSpawnedEntity` already handles the logic for determining which clients should receive entity-related updates. This change reduces code duplication and potential inconsistencies in notification delivery while maintaining the same …
=> Send killfeed to all client with entity spawned

src/servers/ZoneServer2016/managers/groupmanager.ts
Added an alert message when attempting to invite a player who is already in a group
Added a notification that informs players when they try to invite someone who is already in a group, displaying the target player's name in the message
1. Join a group with one character
2. Using another character, try to invite the grouped character
3. Verify you receive the message "[player name] is already in a group!"
Previously, attempting to invite a player who was already in a group would silently fail, providing no feedback to the player. This change improves user experience by clearly communicating why the invite action failed.
=> Display an alert when an invited player is already in a group

src/servers/ZoneServer2016/zoneserver.ts
Added godmode detection to kill feed messages
Added a check to determine if a killer is in godmode when sending kill feed messages. This information is now included in the kill feed packet through the `isCheater` flag.
1. Enable godmode on a character
2. Kill another player
3. Verify that the kill feed indicates the kill was performed with godmode enabled
To provide transparency when players are killed by others using godmode, helping identify potential cheating or abuse of admin privileges in the game.
=> add a special killfeed message when someone kill in godmode

src/servers/ZoneServer2016/handlers/commands/internalcommands.ts
Added automatic god mode activation when players attempt to set high run speeds
Added a safety check that automatically enables god mode for players who set their run speed above 10 without already having god mode enabled
1. Join the game as a regular player
2. Attempt to set run speed above 10
3. Verify god mode is automatically enabled
4. Verify run speed changes are applied
High movement speeds without god mode can cause death.
=> Set godmode when modifying run speed to bugatti

src/servers/ZoneServer2016/entities/character.ts
In the current state if you get headshot by a blaze you are dead, you are not able to premed or outheal it
Now you end up on 16 health with posability of a bleeding effect
=> QOL: Slight nerf to burning tick on Blaze

src/servers/ZoneServer2016/entities/basefullcharacter.ts, src/servers/ZoneServer2016/zoneserver.ts
- Reduced overall item durability to 1000
- Boots, Convey, Gator, and Zed now lose 200 durability upon each death, Effectively grants 5 lives per Convey item
=> Convey durability loss on death

data/2016/dataSources/AccountCrates.json
Fixes an oopsie with Anarchy Leather Pants being in the Infernal Crate
https://survivorsrest.com/h1z1/items/infernal-crate
=> Remove Anarchy Leather Pants from Infernal Crate

src/servers/ZoneServer2016/data/deathitemdamageconfig.ts, src/servers/ZoneServer2016/entities/basefullcharacter.ts, src/servers/ZoneServer2016/zoneserver.ts
Introduced PlayerDeathItemConfig to enable configuration of item IDs and item classes for applying damage to items when a player dies. If an item's durability drops to 0, the configured lootItems are added to the lootbag. Also resolved an issue that prevented items without durability from being included in the lootbag.
=> Reworked getDeathItems logic
