QuentinGruber/h1z1-server

- lib/zonepackethandlers.js
- lib/zoneserver.js
- lib_ts/zonepackethandlers.js
- lib_ts/zoneserver.js
> zonePacketHandlers

- lib/loginpackets.js
- lib/loginserver.js
- lib_ts/loginpackets.js
- lib_ts/loginserver.ts
> fix characterDeleteReply packet schema

- src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.js
> add ClientUpdate.DamageInfo

- data/sampleData/stats.json
- src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.js
i debug all visible mouvement stats of player (speed, move,...)
> debug stats.json

- .gitignore
- package-lock.json
- package.json
- src/protocols/h1z1protocol.ts
- src/servers/ZoneServer/commands/hax.ts
- src/servers/ZoneServer/zonepackethandlers.ts
- src/servers/ZoneServer/zoneserver.ts
- src/types/zoneserver.ts
- tests/testIssuesInPacketSchemas.ts
thx to GuinnesRules for using his code to fix rotations
> Rotation for spawnNpcModel

- src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts
- src/servers/SoeServer/soeserver.ts
- src/servers/ZoneServer/commands/dev.ts
- src/servers/ZoneServer/commands/hax.ts
- src/servers/ZoneServer/workers/createBaseEntities.ts
- src/servers/ZoneServer/zonepackethandlers.ts
- src/servers/ZoneServer/zoneserver.ts
Sorry for ugly code it looks good on notepad++
> Add hax driveTest & hax parachute

- data/2015/sampleData/stats.json
- src/servers/ZoneServer/workers/createBaseEntities.ts
- src/servers/ZoneServer/zonepackethandlers.ts
I took it from fulltest14, it contained ID's up to 40. Comparing to old h1z1 videos it looks alot like it
> Part of proper stats.json

- src/clients/loginclient.ts
- src/clients/zoneclient.ts
- src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts
- src/protocols/h1z1protocol.ts
- src/protocols/soeprotocol.ts
- src/servers/LoginServer/loginserver.ts
- src/servers/ZoneServer/workers/dynamicWeather.ts
- src/servers/ZoneServer/zoneserver.ts
- src/servers/ZoneServer2016/commands/dev.js
Reverts QuentinGruber/h1z1-server#253
> Revert "Autofix"

- src/servers/ZoneServer/commands/hax.ts
- src/servers/ZoneServer/zonepackethandlers.ts
- src/servers/ZoneServer/zoneserver.ts
- src/types/zoneserver.ts
> client.vehicle

- src/packets/ClientProtocol/ClientProtocol_1080/h1z1packets.ts
- src/servers/ZoneServer2016/commands/dev.ts
- src/servers/ZoneServer2016/commands/hax.ts
- src/servers/ZoneServer2016/workers/dynamicWeather.ts
- src/servers/ZoneServer2016/zonepackethandlers.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/types/zoneserver.ts
> Tseverywhere2016

- src/servers/LoginServer/loginserver.ts
- src/servers/ZoneServer2016/zoneserver.ts
single player character creation for 2016
> Character creation

- src/servers/ZoneServer/workers/dynamicWeather.ts
- src/servers/ZoneServer/zonepackethandlers.ts
The ingame time was a raw timestamp, but serverinfo and weather time was affected by timezones
thx to AlvaZhang for identifying and helping solve issue
> Fix timezone issue

- src/servers/ZoneServer/zoneserver.ts
- src/servers/ZoneServer2016/zonepackethandlers.ts
- src/servers/ZoneServer2016/zoneserver.ts
Needed so 2016 server is able to override hooks on the 2015 server (ex. onZoneDataEvent())
> Use functions for event hooks

- .vscode/tasks.json
- src/servers/ZoneServer2016/commands/hax.ts
> added /hax spectate command

- src/servers/ZoneServer/zonepackethandlers.ts
> Vehicle.stateData resending

- src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts
Vehicle.HealthUpdateOwner set's the vehicle health in OwnedVehicle.Info datasource.
Vehicle.AccessType locks the vehicle when l is pressed. Now we just need to add a server variable to check if the vehicle is locked :)
> Added packets

- src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts
Updates the daily ribbon count in Player.Info datasource
> Added ClientUpdate.DailyRibbonCount

- src/servers/ZoneServer/classes/zoneclient.ts
- src/servers/ZoneServer/zonepackethandlers.ts
- src/servers/ZoneServer/zoneserver.ts
Doing it this way server can be up to almost 50 days without the gametime value going out of uint32 range
> fix: synchronization & no player movement

- src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts
Correct structure but cant get it to do anything yet
> Reversed ClientPath

- src/servers/ZoneServer/commands/hax.ts
Removed godmode and dead from /hax state since we got /hax godmode and death to work. I Also added /hax state list :)
> Updated /hax state

- src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts
- src/servers/ZoneServer/classes/character.ts
- src/servers/ZoneServer/commands/dev.ts
- src/servers/ZoneServer/commands/hax.ts
- src/servers/ZoneServer/zonepackethandlers.ts
- src/servers/ZoneServer/zoneserver.ts
✖️ Features in this update ✖️
----------------------------------------------------------------------------------------------------------------------------------------
- Player will now bleed when taking 40% damage in one hit or health is less than 20% and taking any damage.
Could change the value if wanted!
- Added /hax bandage. Will increase health slowly and stop bleeding when health is above 20%.
- Added /dev hideme "So @QuentinGruber  can hide himself from all the fans on live server 🤪 ".
- Decrease stamina if character is bleeding and running. And disable it from increasing while character is bleeding.
- Interactable burlapbag now spawns ontop of player on death
- -------------------------------------------------------------------------------------------------------------------------- …
> Reversed packets and added /dev hideme

- src/servers/ZoneServer/zoneserver.ts
Had the state for godmode wrong :)
> :star2: Players in godmode can now interact with stuff

- src/servers/ZoneServer/zonepackethandlers.ts
Couldnt get fullPc packet to work so i found a workaround 😏 
Or maybe thats the way we should do it.
> bugFix/Multiplayer animations 🔥 💯 

- src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts
- src/servers/ZoneServer/workers/createBaseEntities.ts
that should improve performance a little bit
> Feature/disable fullCharacterDataRequest for some Npcs 🔧 

- src/servers/ZoneServer2016/zoneserver.ts
> 2016 hotFixes/Features

- src/servers/ZoneServer2016/zoneserver.ts
> item definitions are now cached once on server startup

- src/packets/ClientProtocol/ClientProtocol_1080/items.ts
still need to add the new packets to another file, cant remember the name of that file.
> Changed Opcodes and added all Items packets

- src/servers/SoeServer/logicalPacket.ts
- src/servers/SoeServer/soeclient.ts
- src/servers/SoeServer/soeinputstream.ts
- src/servers/SoeServer/soeoutputstream.ts
- src/servers/SoeServer/soeserver.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/types/shared.ts
- src/utils/utils.ts
> CoreOptimizationAndFixes

- src/servers/SoeServer/soeclient.ts
- src/servers/SoeServer/soeoutputstream.ts
- src/servers/SoeServer/soeserver.ts
> OptimizeAckTimings

- src/servers/ZoneServer2016/zoneserver.ts
- src/types/zoneserver.ts
> Combatlog ping

- src/servers/ZoneServer2016/commands/commandhandler.ts
…to use are displayed in /help; internalCommands are now reloaded when using '/dev reloadpackets'; general command handler cleanup
> Command handler cleanup

- src/servers/ZoneServer2016/commands/commands.ts
- src/servers/ZoneServer2016/data/lootspawns.ts
- src/servers/ZoneServer2016/managers/worldobjectmanager.ts
> Weighted lootspawn system

- src/servers/ZoneServer2016/zonepackethandlers.ts
> fixed flying fountation

- src/servers/ZoneServer2016/zoneserver.ts
Need ingame testing but should be ready to go
> fix concurrent saves

- src/servers/ZoneServer2016/zoneserver.ts
removed some innecesary packets/fields
> fix Invis attempt

- src/servers/ZoneServer2016/commands/commands.ts
Allows admins to change names without affecting original name on relogin.
> Added Deepcover command [client-2016]

- src/servers/ZoneServer2016/commands/commands.ts
- src/servers/ZoneServer2016/data/loadouts.ts
> vehicle kit

- README.md
Still a few one missing that i couldnt find the link to. The reason i added the links is that i think we should do proper credits for the ones that actually helped and not just put the names ;)
> Added links to the Thanks List

- src/servers/LoginServer/loginserver.ts
Reverts QuentinGruber/h1z1-server#1610
> Revert "Bugfix/h1emu login server security"

- src/servers/ZoneServer2016/handlers/commands/types.ts
- src/servers/ZoneServer2016/managers/pluginmanager.ts
> Added built-in support for plugins adding their own commands

- src/servers/ZoneServer2016/zonepackethandlers.ts
- src/types/shared.ts
> Detect Typo Errors

- package-lock.json
- package.json
> Support Mongo 7

- .github/workflows/dev-test.yml
- .github/workflows/release-test.yml
- .github/workflows/release.yml
- package-lock.json
- package.json
- src/servers/LoginZoneConnection/shared/baselzconnection.ts
- src/servers/SoeServer/soeclient.ts
> Support node 20

- data/2016/sampleData/defaultconfig.yaml
- src/servers/ZoneServer2016/entities/constructiondoor.ts
- src/servers/ZoneServer2016/managers/configmanager.ts
- src/servers/ZoneServer2016/models/config.ts
- src/servers/ZoneServer2016/zonepackethandlers.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/utils/enums.ts
> miscAndFixes

- src/servers/ZoneServer2016/handlers/commands/commands.ts
https://streamable.com/d76l15
someone in NTC told me that 1k had found this, but never reported it (more than likely abusing the hell out of it). Simple fix that checks animationId for 35 and if so exits the function.
> Emote 35 exploit fix

- data/2016/sampleData/defaultconfig.yaml
- src/servers/ZoneServer2016/entities/baselootableentity.ts
- src/servers/ZoneServer2016/entities/lootableprop.ts
- src/servers/ZoneServer2016/entities/npc.ts
- src/servers/ZoneServer2016/entities/zombie.ts
- src/servers/ZoneServer2016/handlers/commands/commands.ts
- src/servers/ZoneServer2016/managers/configmanager.ts
- src/servers/ZoneServer2016/models/config.ts
- src/servers/ZoneServer2016/zoneserver.ts
This PR contains the following changes:
* Fixed an issue causing lootbags not to despawn
* Fixed an issue with zombies, the timer would initiate without having the required item
* Fixed an issue that caused the whisper target to not receive whispers
* Fixed an issue that caused zombies to despawn when shot in the head.
* Crowbars scrap chance and damage can now be configured by the server owner
> Minor fixes

- src/servers/ZoneServer2016/handlers/commands/commands.ts
I blew it lol. 
Now we're actually targeting the right player...
> targeting the local client instead of the actual target :/

- src/servers/ZoneServer2016/data/Recipes.ts
https://streamable.com/a4p29m 
Fix for #1755.
> Fix for bear meat not cooking

- src/servers/ZoneServer2016/managers/constructionmanager.ts
Fixed their models which fixes #1743. Gonna look into fixing rigged lights and corn mash as their logic doesn't seem too difficult to implement.
> Fix corn mash and rigged light models

- src/servers/ZoneServer2016/entities/vehicle.ts
> Fix for wrench not working on PVE

- src/servers/ZoneServer2016/entities/trapentity.ts
Reported by @DaEgo barb wire should dmg players inside of vehicles
> Barbed wire damaging players in vehicle

- README.md
---
> ## TL;DR
> This pull request includes minor changes to the README.md file, improving the formatting and readability of the document.
> 
> - Removed unnecessary blank lines.
> - Changed the mention of a user from `@jseidelin` to a hyperlink to the user's GitHub profile.
> - Adjusted the formatting of the bullet points under the "examples" and "Demo" sections for better readability.
> 
> To test these changes, view the README.md file on the repository's main page. Ensure that the changes have improved the readability and overall structure of the document.
> 
> ## Why make this change
> These changes were made to improve the …
> Fix Readme so it properly render on doc

- src/servers/ZoneServer2016/entities/lootableconstructionentity.ts
- src/servers/ZoneServer2016/zonepackethandlers.ts
Got this info from KronicWayz 👍 hand shovel stashes shouldn't glow and also change the name_id to 1698 which makes it say "open stash" rather than "open hand shovel"
> Hand shovel changes

- src/servers/ZoneServer2016/handlers/commands/commands.ts
---
> # Pull Request Description
> 
> ## TL;DR
> This pull request simplifies the process of finding a character in the `commands.ts` file by removing unnecessary checks and using a more direct approach.
> 
> The previous code was checking for offline characters first for an exact match, and if not found, it was trying to get the client by login session ID. This has been simplified to directly get the character from the database using the owner ID. If the character is not found, it defaults the character name to "unknownCharacterName".
> 
> To test this change, you can use the command that triggers this code block with different …
> Fix /banid

- src/servers/ZoneServer2016/handlers/commands/commands.ts
- src/servers/ZoneServer2016/managers/fairplaymanager.ts
- src/servers/ZoneServer2016/managers/weathermanager.ts
- src/servers/ZoneServer2016/zonepackethandlers.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/utils/utils.ts
---
> ## TL;DR
> This pull request makes changes to several files in the project. It adds a new function `getCurrentTimeWrapper()` and a new class `TimeWrapper` to handle time-related operations. It also modifies existing code to use these new functions and classes for calculating uptime, server time, and game time.
> 
> - Added a new function `getCurrentTimeWrapper()` in the `utils.ts` file to get the current time as a `TimeWrapper` object.
> - Added a new class `TimeWrapper` in the `utils.ts` file to handle time-related operations.
> - Modified the `commands.ts` file to use the `getCurrentTimeWrapper()` function for calculating uptime.
> - Modified the …
> Implement a time wrapper for cleaner code

- src/servers/LoginServer/loginserver.ts
- src/types/loginserver.ts
---
> ## TL;DR
> This pull request makes changes to the `loginserver.ts` and `loginserver.ts` files. It adds new types `GameServer` and `BannedUser` to the `loginserver.ts` file. It also modifies the `LoginServer` class by adding a new property `_db` of type `Db` and making it non-nullable. It removes the `_isServerOfficial` method and modifies the `parseData` and `ServerListRequest` methods. It also adds a new method `getClientRejectionFlags` and modifies the `CharacterLoginRequest` method.
> 
> - Added new types `GameServer` and `BannedUser` to the `loginserver.ts` file.
> - Modified the `LoginServer` class by adding a new property `_db` of type `Db` …
> Check global bans & clean some type stuff in loginserver

- src/servers/ZoneServer2016/managers/speedtreemanager.test.ts
---
> ## TL;DR
> This pull request introduces a new test file for the `SpeedTreeManager` class in the `ZoneServer2016` module. The tests cover the `initiateList`, `destroy`, and `customize` methods of the `SpeedTreeManager` class.
> 
> A new test file `speedtreemanager.test.ts` was added to the `ZoneServer2016/managers` directory. This file contains tests for the `SpeedTreeManager` class, specifically the `initiateList`, `destroy`, and `customize` methods.
> 
> To test these changes, follow these steps:
> 
> 1. Pull the changes from this branch into your local environment.
> 2. Navigate to the root directory of the project.
> 3. Run the …
> Write tests for speedtree manager

- src/servers/ZoneServer2016/zoneserver.ts
> Add initialStaticDTO caching x10 faster

- src/servers/GatewayServer/gatewayserver.threaded.ts
- src/servers/GatewayServer/gatewayserver.ts
- src/servers/GatewayServer/gatewayserver.worker.ts
- src/servers/ZoneServer2015/zonepackethandlers.ts
- src/servers/ZoneServer2015/zoneserver.ts
- src/servers/ZoneServer2016/handlers/commands/commands.ts
- src/servers/ZoneServer2016/handlers/commands/dev.ts
- src/servers/ZoneServer2016/managers/fairplaymanager.ts
- src/servers/ZoneServer2016/zoneserver.ts
---
> ## TL;DR
> This pull request includes various changes to different files and classes in the codebase. The changes involve replacing parameters, adding new functions, modifying existing functions, and updating event handlers. The goal of these changes is to improve the retrieval and display of network statistics, handle client disconnections, and make the code more efficient and readable.
> 
> - Replaced the "client" parameter with "client.soeClientId" in the "login" event and "client.sessionId" in the "disconnect" event in the "gatewayserver.ts" file.
> - Added functions to retrieve the average ping, network statistics, and session ID of a specific …
> Refactor Gateway Server to use SoeClientId instead of the full object

- src/servers/GatewayServer/gatewayserver.threaded.ts
---
> ## TL;DR
> This pull request modifies the way the worker path is defined in the `GatewayServerThreaded` class. Instead of hardcoding the path, it now uses the `path` module from Node.js to join the current directory name (`__dirname`) with the worker file name.
> 
> The hardcoded worker path in the `GatewayServerThreaded` constructor has been replaced with a dynamic path using the `path` module. This change affects the instantiation of the `Worker` object.
> 
> To test this change, you can instantiate a `GatewayServerThreaded` object and check if the worker is correctly created. You can also run any existing unit tests that involve …
> Path.join current dir for gateway worker

- src/protocols/h1z1protocol.ts
- src/servers/ZoneServer2016/zonepackethandlers.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/types/protocols.ts
this is just a test that i wanna save so plz don't mind until it is actually something cool
> Faster broadcast

- src/servers/LoginServer/loginserver.ts
> Fix global bans propagation

- src/servers/ZoneServer2016/entities/character.ts
- src/servers/ZoneServer2016/zoneserver.ts
Fixing some more stuff from #1740. Cant test number different arrow types, but I'll add daego in the morning to see if there's any other PvE stuff that needs to be looked into. The method used for detecting explosives on pve didn't work so just changed the logic and add some checks around 👍
> Fix explosive damage and melee/projectilehits damaging armor and helmets

- src/servers/ZoneServer2016/entities/character.test.ts
- src/servers/ZoneServer2016/entities/character.ts
- src/utils/test.utils.ts
---
> ## TL;DR
> This pull request introduces tests for the damage system in both PvE and PvP modes. It also adds a `getHealth` method to the `Character2016` class and utility functions to create fake characters and clients for testing purposes.
> 
> 1. **New Test File:** A new test file `character.test.ts` was added under `src/servers/ZoneServer2016/entities/`. This file contains tests for the damage system in both PvE and PvP modes.
> 
> 2. **New Method in Character2016:** A new method `getHealth` was added to the `Character2016` class in `src/servers/ZoneServer2016/entities/character.ts`. This method returns the health of the character.
> 
> 3. **New …
> Add characters damage unit tests

- src/servers/ZoneServer2016/entities/lootableconstructionentity.ts
> Fix for demo hammer melee on bee box

- src/servers/ZoneServer2016/classes/collectingentity.ts
- src/servers/ZoneServer2016/managers/smeltingmanager.ts
https://survivorsrest.com/justsurvive/patchnotes 
https://www.reddit.com/r/h1z1/comments/34szqk/bee_box/
https://www.reddit.com/r/h1z1/comments/32vnw6/how_do_i_work_with_bee_box/
https://www.reddit.com/r/h1z1/comments/39u28b/question_about_bee_boxs/
(Look at comments in reddit posts)
In the april 15, 2015 update, DBG added bee boxes and also made it so a maximum of 5 honeycomb and 10 honey can be inside a bee box at one time, so this PR is to reflect that. While researching about this, I also found that honeycomb spawn times were ~6 hours or so. We unfortunately don't have the luxury of a video where someones standing at a bee box for 6 hours, but I did manage to find multiple reddit posts from r/H1Z1 where people said honeycomb spawns in around ~6 hours. So also changed that :D
> Honey and honeycomb inside bee boxes

- src/servers/ZoneServer2016/zonepackethandlers.ts
> fixed fairplay kicks in vehicle

- src/servers/ZoneServer2016/entities/npc.ts
I believe it was for the old harvesting system so it's no longer needed ?
> Remove old logic about npc corpse

- src/servers/ZoneServer2016/managers/worldobjectmanager.ts
Reverts QuentinGruber/h1z1-server#1907
> Revert "Fix containers not receiving entirety of loottable upon respawn"

- src/servers/ZoneServer2016/managers/worlddatamanager.test.ts
interesting that the tests fails
> Add constructions to world save unit tests

- src/servers/ZoneServer2016/zoneserver.ts
- src/utils/enums.ts
I don't know if we add a command to add a new whitelisted or if we await to have the rcon server and do that there
> Add vpn-whitelist

- src/servers/ZoneServer2016/entities/npc.ts
- src/servers/ZoneServer2016/zoneserver.ts
Reverts QuentinGruber/h1z1-server#1933
somehow it break the game, making it crash and much more bad stuff
> Revert "Skinning knife durability & damaging"

- src/servers/ZoneServer2016/managers/worldobjectmanager.ts
---
> ## TL;DR
> This pull request removes a temporary fix that was disabling fences in the game due to glitching graphics. The glitch has been resolved, so fences can now be re-enabled.
> 
> In the `WorldObjectManager` class, we had a condition that was skipping over any object that had "fence" in its actor file name. This was to avoid a glitching graphics issue. This pull request removes that condition, effectively re-enabling fences in the game.
> 
> ```diff
> -      // disable fences until we find a fix for glitching graphics
> -      if (propType.actor_file.toLowerCase().includes("fence")) return;
> ```
> 
> To test this change, you …
> Renable wood fence destruction

- src/servers/ZoneServer2016/handlers/commands/commands.ts
Refer to #1930 and Kentins comment - ty jason
> Containers respawn command

- src/servers/ZoneServer2016/data/useoptions.ts
- src/servers/ZoneServer2016/entities/constructionchildentity.ts
- src/servers/ZoneServer2016/entities/taskprop.ts
- src/servers/ZoneServer2016/entities/vehicle.ts
Refer to #1930 and Kentins comment
> Other Loot timer stuff

- src/servers/ZoneServer2016/handlers/commands/commands.ts
I noticed while testing #2042 that doing /additem will give you randomized durability (if the item qualifies), so this PR adds the boolean to generateItem in the addItem function.
> Max durability for /additem

- src/servers/ZoneServer2016/zoneserver.ts
Re-implements Avcio's change that made players need to search containers before items display in proximity.
> Search Containers before displaying proximity

- src/servers/ZoneServer2016/zonepackethandlers.ts
> Fixed a bug with applying skins to inventory items

- src/packets/ClientProtocol/ClientProtocol_1080/dto.ts
- src/servers/ZoneServer2016/entities/destroyable.ts
i want to test something, maybe modifying assets could fix that
> renable wood fences destruction

- src/servers/ZoneServer2016/zoneserver.ts
Refactor to use async/await in the saveWorld method of ZoneServer2016.
The saveWorld method in src/servers/ZoneServer2016/zoneserver.ts was refactored to use async/await instead of promise chaining. This enhances code readability and maintainability.
Ensure that the world saving functionality still works as expected. Specifically, verify that the world data (characters, constructions, crops, traps, vehicles, etc.) is correctly saved and that proper notifications are sent to admins.
This change was made to improve the readability and maintainability of the code by leveraging modern JavaScript features.
---
> Properly await for world save

- src/servers/SoeServer/soeserver.ts
on master https://github.com/QuentinGruber/h1z1-server/commit/3044bd9179af390d483007f6d6621d23494dbf28
> Fix performance observer mem leak

- src/servers/ZoneServer2016/managers/constructionmanager.ts
- src/servers/ZoneServer2016/managers/speedtreemanager.test.ts
- src/servers/ZoneServer2016/managers/speedtreemanager.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/types/zonedata.ts
- src/types/zoneserver.ts
- src/utils/utils.ts
- **rename speedtree property to speedtreedestroyed**
- **speedtreelist as a map**
- **remove allowedTrees for constructions from Z1_speedTrees.json**
- **use foreach from map**
- **remove treeId field**
> optimiseSpeedTreeManager

- .eslintrc.json
- eslint.config.mjs
- package-lock.json
- package.json
- src/packets/ClientProtocol/ClientProtocol_1080/weapon.ts
- src/servers/LoginServer/loginserver.ts
- src/servers/SoeServer/soeserver.ts
- src/servers/ZoneServer2016/entities/character.ts
- src/servers/ZoneServer2016/entities/doorentity.ts
- src/servers/ZoneServer2016/entities/itemobject.ts
- src/servers/ZoneServer2016/handlers/commands/commands.ts
- src/servers/ZoneServer2016/handlers/commands/dev.ts
- src/servers/ZoneServer2016/managers/configmanager.ts
- src/servers/ZoneServer2016/managers/constructionmanager.ts
- src/servers/ZoneServer2016/managers/pluginmanager.ts
- src/servers/ZoneServer2016/managers/worlddatamanager.ts
- src/servers/ZoneServer2016/managers/worldobjectmanager.ts
- src/servers/ZoneServer2016/zonepackethandlers.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/utils/utils.ts
- **updt eslint + migrate config**
- **wip**
> updtDeps(eslint)

- data/2016/zoneData/Z1_taskProps.json
- src/servers/ZoneServer2016/entities/taskprop.ts
- src/servers/ZoneServer2016/zoneserver.ts
Added a gravestone with some goodies, the stash should only spawn every wipe.
> For our dear friend

- src/servers/SoeServer/soeserver.ts
- src/servers/ZoneServer2016/managers/worlddatamanager.ts
- src/types/savedata.ts
- **udp6 -> udp4**
- **rename lastdropplaytime**
> small fixes

- README.md
Add a table of contents and new sections to the `README.md` for better navigation and information.
- **Table of Contents**: Add a table of contents at the beginning of the README for easier navigation.
- **Contributing Section**: Add a "Contributing" section with a link to `CONTRIBUTING.md`.
- **License Section**: Add a "License" section with a link to `LICENSE`.
- **Usage Examples**: Add detailed usage examples, including starting the server and connecting to it.
- **Troubleshooting**: Add troubleshooting tips for common issues like server not starting and client not connecting.
- **Development Environment**: Add a section on how to set up a simple development environment, including cloning the repository, installing dependencies, and starting the development server.
---
For more …
> Improve README with detailed instructions and examples

- src/packets/LoginUdp/LoginUdp_11/loginpackets.ts
- src/servers/LoginServer/loginserver.ts
- src/servers/ZoneServer2016/entities/character.ts
- src/servers/ZoneServer2016/handlers/commands/commands.ts
- src/servers/ZoneServer2016/zonepackethandlers.ts
- src/types/LoginUdp_11packets.ts
1. Restored the population level.
2. Players inside a shelter should no longer receive damage, unless the door is open, of course.
> Minor changes

- src/packets/ClientProtocol/ClientProtocol_1080/shared.ts
- src/protocols/h1z1protocol.ts
- **do not concat buffers and remove unused func**
- **do not allocate unused bytes with packUnsignetIntWith2bitLengthValue**
> optimize broadcast

- src/servers/ZoneServer2016/managers/groupmanager.ts
- src/servers/ZoneServer2016/zoneserver.ts
> Update groups for offline players

- src/servers/LoginServer/loginserver.ts
- src/servers/ZoneServer2016/managers/fairplaymanager.ts
- src/utils/enums.ts
- **rm ASSET_HASHES from db**
- **rm workaround**
> remove assets hashs from db

- src/servers/ZoneServer2016/entities/lootableprop.ts
- src/servers/ZoneServer2016/entities/treasurechest.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/utils/utils.ts
…ps and treasure chest drop rate
> another crate drop rework

- src/packets/ClientProtocol/ClientProtocol_1080/shared.ts
- src/protocols/h1z1protocol.ts
- src/servers/SoeServer/soeserver.ts
- src/servers/ZoneServer2016/entities/character.ts
- src/servers/ZoneServer2016/entities/vehicle.ts
- src/servers/ZoneServer2016/zonepackethandlers.ts
- src/servers/ZoneServer2016/zoneserver.ts
…resendTimeout and maxResendTries
> quick Fixes

- src/servers/ZoneServer2016/handlers/commands/dev.ts
- src/servers/ZoneServer2016/zonepackethandlers.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/types/zoneserver.ts
- **add dev c**
- **display when a player open a rare item**
> alert when a rare is opened

- src/servers/ZoneServer2016/handlers/commands/commands.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/types/zoneserver.ts
- **save adminId in logs instead of adminName**
- **remove unneeded await keywords**
> adminIdInLogs

- data/2016/zoneData/Z1_nerfedPOIs.json
- src/servers/ZoneServer2016/data/lootspawns.ts
- src/servers/ZoneServer2016/managers/fairplaymanager.ts
- src/servers/ZoneServer2016/managers/worlddatamanager.ts
- src/servers/ZoneServer2016/managers/worldobjectmanager.ts
- src/servers/ZoneServer2016/zoneserver.ts
> slight buggs, disable some checks to improve hitreg

- src/servers/ZoneServer2016/entities/taskprop.ts
updated part of coded message to be always in treasurechest
> Hospital changes#2

- src/servers/ZoneServer2016/zoneserver.ts
Reverts QuentinGruber/h1z1-server#2295 ffs @Nikolassparrow test your prs properly when the player respawn it respawn in the car
> Revert "Bugfix/locked vehicle on death"

- src/servers/ZoneServer2016/data/lootspawns.ts
> nerfed ferts

- src/servers/ZoneServer2016/zoneserver.ts
- **check if vehicle exist first**
- **get var data inside event**
- https://github.com/QuentinGruber/h1z1-server/pull/2322
> fixVehicleLOckingCrash

- src/servers/ZoneServer2016/zonepackethandlers.ts
Reported by: Eric and ben dover in discord
Fix for #2379
> Fix convey skins losing durability upon skinning

- src/servers/ZoneServer2016/entities/trapentity.ts
https://www.reddit.com/r/h1z1/comments/37ew59/game_update_527/
In the may 26th, 2015 update, DBG added a small resistance to punji stick damage, although I couldn't find the exact resistance amount, I set it to a 20% resistance (401)
> Add small resistance to boots

- src/servers/ZoneServer2016/entities/trapentity.ts
Reverts QuentinGruber/h1z1-server#2386 if only has boots existed @Nikolassparrow maybe you forgot to push it ?
> Revert "Add small resistance to boots"

- src/servers/ZoneServer2016/managers/rewardmanager.ts
> added new crate to rotation

- src/servers/ZoneServer2016/entities/lootableprop.ts
One of the cabinets from #2347 was incorrect so fixed that, and move a cabinet into interaction string that i missed
> Fix cabinet interaction string and move cabinet type

- src/servers/ZoneServer2016/managers/groupmanager.ts
Add the ability to transfer group leadership so we don’t have to remake the group.
> Feat: Group transfer leader

- .github/workflows/release-test.yml
- .github/workflows/release.yml
- **publish-a-next-version**
- **updt hash**
- **publish-a-next-version**
- **hash again**
- **'publish-a-next-version'**
- **im about to explode**
- **last try**
- **'publish-a-next-version'**
- **rm logs**
- **publish-a-next-version**
- **updt voice server ip**
- **publish-a-next-version**
- **fix docker actions**
> fix docker actions

- src/servers/ZoneServer2016/entities/npc.ts
- src/servers/ZoneServer2016/entities/vehicle.ts
- src/servers/ZoneServer2016/handlers/commands/commands.ts
- src/servers/ZoneServer2016/zoneserver.ts
- src/utils/enums.ts
- src/utils/utils.ts
- **add /stats command**
- **add vehicle kills to /kills**
- **implement /stats**
> player stats

- src/servers/ZoneServer2016/entities/vehicle.ts
https://discord.com/channels/707525351357677610/1330604893245018206
> Fix magnum and 308 to damage vehicles at 8% per shot 

- src/servers/ZoneServer2016/entities/crate.ts
- src/servers/ZoneServer2016/entities/destroyable.ts
- src/servers/ZoneServer2016/managers/speedtreemanager.ts
- src/servers/ZoneServer2016/zoneserver.ts
https://h1z1stuff.weebly.com/melee-weapons.html
Got all my information about durability, and their damages here ^
> Add durability damage to tools when meleeing

- src/servers/ZoneServer2016/managers/constructionmanager.ts
- src/servers/ZoneServer2016/models/enums.ts
- **allow placement of wooden-barricade**
- **allow placement of wooden-barricade in POI**
> wooden barricade

- src/servers/ZoneServer2016/zoneserver.ts
Increase the range of the flashbang, as it feels too small.
Remove the check that prevents refueling from any seat.
> minnor changes

- src/servers/ZoneServer2016/data/Recipes.ts
* Also added the R380 to the melt table
* Added M1911 to Dismantle next to weapon workbench for gun parts
Not able to add multiple guns to dismantle into gun parts due to errors
> Added skinned guns to melt table

- .gitignore
- src/servers/ZoneServer2016/zoneserver.ts
Nerf mollys
and added .env to .gitignore
> Nerf mollys

- data/2016/zoneData/Z1_nerfedPOIs.json
- src/servers/ZoneServer2016/data/lootspawns.ts
- src/servers/ZoneServer2016/managers/worldobjectmanager.ts
> loottable changes

- src/servers/ZoneServer2016/entities/plant.ts
- src/servers/ZoneServer2016/zoneserver.ts
bumped from 15 seconds to 3, minutes making you able to actually know what tillers you´ve ferted & not
> QOL - Increased visual effect on ferted tillers

- package.json
- src/servers/ZoneServer2016/entities/plantingdiameter.ts
- src/servers/ZoneServer2016/managers/worlddatamanager.ts
- src/types/savedata.ts
add the ability to demo groud tiller.
add the ability to undo groud tiller.
> Demo tillers

- src/servers/ZoneServer2016/handlers/commands/commands.ts
- src/servers/ZoneServer2016/managers/groupmanager.ts
More TP locations added to the map
Added missed command ''Leader'' Requested by @johnoclockdk 
Removed ''pointless'' command ''Drylake''
> Commands update

- src/servers/ZoneServer2016/classes/loadoutcontainer.ts
- src/servers/ZoneServer2016/entities/vehicle.ts
- src/servers/ZoneServer2016/managers/constructionmanager.ts
- src/servers/ZoneServer2016/managers/worlddatamanager.ts
- src/servers/ZoneServer2016/zoneserver.ts
* Added the possability to put Honeycomb inside bee boxes
* Fixed text on wrench showing incorrect durability & lowered the durability (100 per hit down to 80 per hit) to maintain a full wrench to 25 hits
Before 2500/2000 Durability
Now 2000/2000 Durability
> QOL Changes

- src/servers/ZoneServer2016/handlers/commands/commands.ts
I made it so that the message is always sent, even if the player doesn't exist, because players were using it to check if someone is online.
> Commands(whisper)

- src/servers/ZoneServer2016/handlers/commands/commands.ts
giverewardtoall command prettified
> giverewardtoall command prettified

- src/servers/ZoneServer2016/zoneserver.ts
- src/utils/utils.ts
This allows you to loot container & Lootbags from underneath
Thanks @johnoclockdk for the assistance on this one!
> Looting Lootbag/Container underneath

- src/servers/ZoneServer2016/data/useoptions.ts
added use options for ''raw'' corn as it only gave an error message before
> Add use options for (raw) Corn
